---
title: "1st_draft"
author: "Yifan Du"
date: "12/6/2021"
output: html_document
---

```{r, echo = F, message = F, warning = F}
library(tidytext)
library(tidyr)
library(dplyr)
library(readr)
library(tm)
library(SnowballC)
library(stringr)
library(udpipe)
udmodel <- udpipe_download_model(language = "english")
udmodel <- udpipe_load_model(file = udmodel$file_model)


```


```{r, echo = F}
data_2 <- read.csv("../Data/camera.csv") %>% filter(word.stem != "br" & word.stem != "camera")


data_2$star_rating <- data_2$star_rating %>% factor

data_2$star_rating <- str_c("star_",data_2$star_rating)

noun <- udpipe_annotate(udmodel, 
                     unique(data_2$word.stem)) %>% 
  as.data.frame() %>% 
  select(token, upos) %>% filter(upos == "NOUN") %>% unlist

data_3 <- data_2 %>% filter(word.stem %in% noun) %>% 
  group_by(word.stem) %>%
  summarise(all_freq = sum(frequency)) 

data_4 <- data_2 %>% select(-X) %>% 
  spread(star_rating, frequency)





most_freq_word <- data_3$word.stem[order(data_3$all_freq,decreasing = T)] %>% 
  head(30)

library(ggplot2)
word="refund"
print(data_2 %>%
        filter(word.stem == word) %>%
        ggplot()+
        geom_bar(aes(x = star_rating,y = frequency,fill = star_rating),stat = "identity")+
        ggtitle(word))


data_4$word.stem[data_4$star_3<data_4$star_2]


```


```{r, echo = F}

for( word in most_freq_word){
print(data_2 %>%
  filter(word.stem == word) %>%
  ggplot()+
    geom_bar(aes(x = star_rating,y = frequency,fill = star_rating),stat = "identity")+
    ggtitle(word) )
}
